replicaCount: 1

image:
  repository: europe-west3-docker.pkg.dev/sonorous-stone-498307-u2/weather-app-frontend/weather-app-frontend
  tag: "v1.3.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: weather.inenp.werschlan.at
  hosts:
    - host: weather.inenp.werschlan.at
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: weather-frontend-tls
      hosts:
        - weather.inenp.werschlan.at
