replicaCount: 1

image:
  repository: europe-west3-docker.pkg.dev/sonorous-stone-498307-u2/weather-app-backend/weather-app-backend
  tag: "v1.3.1"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
