apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.21.*
    helm:
      values: |
        provider:
          name: google
        extraArgs:
          - --google-project=sonorous-stone-498307-u2
          - --domain-filter=inenp.werschlan.at
        serviceAccount:
          create: true
          name: external-dns
        policy: upsert-only
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
