apiVersion: sql.gcp.m.upbound.io/v1beta1
kind: Database
metadata:
  name: weather-app
  annotations:
    crossplane.io/external-name: weather_app
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    instanceRef:
      name: weather-app-db
  providerConfigRef:
    name: default
