apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: platform

  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.3.2
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/platform/crossplane/values.yaml
    - repoURL: https://github.com/MCCE-2025/SS2026-INENP-GitOps
      targetRevision: feat/argocd-gitops-bootstrap
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
